### ISSUE TITLE
Compil error 

### ISSUE THREAD

**Issue by bobkhan** [M0ra/Core#1]
Очень много ошибки при компиляции 
VC2012
ver:c0364819e668e8d59c78daad63432439e89c76cf

видел там много хороший патчей, если можно еще добавь VIP_account

A lot of errors when compiling
VC2012
ver:c0364819e668e8d59c78daad63432439e89c76cf
google :))

**Comment by M0ra** [comment]
На линуксе собирается отлично, в ядре много тестового скрипта, который в дальнейшем будет исправляться.

**Comment by bobkhan** [comment]
Привет,
Извини за скрипт (TOC) на Тринику  поставил если против могу удалить. я думал что это паблик  ).

**Comment by bobkhan** [comment]
а еще У те база ТДБ или ЮТДБ?

**Comment by M0ra** [comment]
Привет.
@bobkhan такими вещами ты вынуждаешь меня сделать приват-репо.( я по поводу ТОС)
с ТДБ перешёл на ЮТДБ(Перестроенную под ядро)

**Comment by bobkhan** [comment]
ясно сорри
