### ISSUE TITLE
boss_yogg_saron

### ISSUE THREAD

**Issue by w5860363** [M0ra/Core#16]
boss_sara By Shadow Nova after injury（http://wotlk.openwow.com/spell=62714）Automatic back to full life And no phase transition

Please excuse my English.

**Comment by w5860363** [comment]
set 33280 flags_extra 1 is work

**Comment by w5860363** [comment]
But the trigger is visible

**Comment by iraj0711** [comment]
compile errore.

**Comment by w5860363** [comment]
@M0ra test yogg_saro Not working properly, there is no neutral monsters inside the room, return to normal TC test
