### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by w5860363** [M0ra/Core#18]
class npc_hodirs_fury : public CreatureScript
{
public:
    npc_hodirs_fury() : CreatureScript("npc_hodirs_fury") { }

```
struct npc_hodirs_furyAI : public ScriptedAI
{
    npc_hodirs_furyAI(Creature* creature) : ScriptedAI(creature)
    {
        me->setActive(true);
        me->SetReactState(REACT_PASSIVE);
        me->AddAura(SPELL_BLUE_SKYBEAM, me);
        me->SetDisplayId(me->GetCreatureTemplate()->Modelid2);
        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
    }

    void Reset()
    {
        _targetGUID.Clear();
        _action = 3;
        _timer = 3 * IN_MILLISECONDS;
    }

    void UpdateAI(uint32 diff)
    {
        if (_timer <= diff)
        {
            switch (_action)
            {
            case 1:
            {
                _timer = 1 * IN_MILLISECONDS;

                Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID);
                if (target && me->IsInRange(target, 0.0f, 5.0f, false))
                {
                    me->GetMotionMaster()->Clear();
                    me->GetMotionMaster()->MoveIdle();
                    _timer = 3 * IN_MILLISECONDS;
                    _targetGUID.Clear();
                    ++_action;
                }
                else if (!target)
                    _action = 3;

                break;
            }
            case 2:
                if (Creature* trigger = DoSummonFlyer(NPC_HODIR_BEACON, me, 50.0f, 0, 10 * IN_MILLISECONDS, TEMPSUMMON_TIMED_DESPAWN))
                {
                    DoCast(trigger, SPELL_HODIR_S_FURY, true);
                    trigger->SetDisplayId(trigger->GetCreatureTemplate()->Modelid2);
                    ++_action;
                }
                _timer = 7 * IN_MILLISECONDS;
                break;
            case 3:
                DoZoneInCombat(me, 200.0f);
                if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                {
                    _targetGUID = target->GetGUID();
                    me->GetMotionMaster()->MoveFollow(target, 0.0f, 0.0f);
                    _action = 1;
                }
                _timer = 5 * IN_MILLISECONDS;
            }
        }
        else
            _timer -= diff;
    }

private:
    ObjectGuid _targetGUID;
    uint32 _timer;
    uint8 _action;
};

CreatureAI* GetAI(Creature* creature) const
{
    return new npc_hodirs_furyAI(creature);
}
```

};

**Comment by w5860363** [comment]
CreatureAI.H
void DoZoneInCombat(Creature* creature = NULL, float maxRangeToNearestTarget = 50.0f);
		+void DoAttackerAreaInCombat(Unit* attacker, float range, Unit* pUnit = NULL);

        CreatureAI.CPP
void CreatureAI::DoAttackerAreaInCombat(Unit* attacker, float range, Unit* pUnit)
{
	if (!attacker)
		attacker = me;
	
		if (!pUnit)
		pUnit = me;
	
		Map *map = pUnit->GetMap();
	
		if (!map->IsDungeon())
		 return;
	
		if (!pUnit->CanHaveThreatList() || pUnit->getThreatManager().isThreatListEmpty())
		return;
	
		Map::PlayerList const &PlayerList = map->GetPlayers();
	for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
		{
		if (Player* i_pl = i->GetSource())
			if (i_pl->IsAlive() && attacker->GetDistance(i_pl) <= range)
			{
			pUnit->SetInCombatWith(i_pl);
			i_pl->SetInCombatWith(pUnit);
			pUnit->AddThreat(i_pl, 0.0f);
			}
		}
	}

In accordance with the requirements of skills

**Comment by M0ra** [comment]
what you want to offer? :)

**Comment by w5860363** [comment]
@M0ra The skills should be continuous cycle, and continue to search after the attack
But I am not sure I can use correct grammar

**Comment by w5860363** [comment]
I think 
enum HodirsFuryEvents
{
	EVENT_SELECT_TARGET_AND_FOLLOW = 1,
	EVENT_STOP_FOLLOWING,
	EVENT_SUMMON_HODIRS_BEACON
};

class npc_hodirs_fury : public CreatureScript
{
public:
	npc_hodirs_fury() : CreatureScript("npc_hodirs_fury") { }

	struct npc_hodirs_furyAI : public ScriptedAI
	{
		npc_hodirs_furyAI(Creature* creature) : ScriptedAI(creature)
		{
			me->setActive(true);
			me->SetReactState(REACT_PASSIVE);
			me->AddAura(SPELL_BLUE_SKYBEAM, me);
			me->SetDisplayId(me->GetCreatureTemplate()->Modelid2);
			me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
		}

		void Reset()
		{
			_targetGUID.Clear();
			_action = 3;
			_timer = 3000;
		}

		void UpdateAI(uint32 diff)
		{
			if (_timer <= diff)
			{
				switch (_action)
				{
				case 1:
				{
						  _timer = 1000;

						  Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID);
						  if (target && me->IsInRange(target, 0.0f, 5.0f, false))
						  {
							  me->GetMotionMaster()->Clear();
							  me->GetMotionMaster()->MoveIdle();
							  _timer = 3000;
							  _targetGUID.Clear();
							  ++_action;
						  }
						  else if (!target)
							  _action = 3;

						  break;
				}
				case 2:
					if (Creature* trigger = DoSummonFlyer(NPC_HODIR_BEACON, me, 50.0f, 0, 10000, TEMPSUMMON_TIMED_DESPAWN))
					{
						DoCast(trigger, SPELL_HODIR_S_FURY, true);
						trigger->SetDisplayId(trigger->GetCreatureTemplate()->Modelid2);
						++_action;
					}
					_timer = 7000;
					break;
				case 3:
					DoZoneInCombat(me, 200.0f);
					if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
					{
						_targetGUID = target->GetGUID();
						me->GetMotionMaster()->MoveFollow(target, 0.0f, 0.0f);
						_action = 1;
					}
					_timer = 5000;
				}
			}
			else
				_timer -= diff;
		}

	private:
		ObjectGuid _targetGUID;
		uint32 _timer;
		uint8 _action;
	};

	CreatureAI* GetAI(Creature* creature) const
	{
		return new npc_hodirs_furyAI(creature);
	}
};

To solve the problem

**Comment by M0ra** [comment]
Tested. hard for me, I'm from a mobile device

class npc_hodirs_fury : public CreatureScript
{
public:
    npc_hodirs_fury() : CreatureScript("npc_hodirs_fury") { }

    struct npc_hodirs_furyAI : public ScriptedAI
    {
        npc_hodirs_furyAI(Creature* creature) : ScriptedAI(creature)
        {
            me->setActive(true);
            me->SetReactState(REACT_PASSIVE);
            me->AddAura(SPELL_BLUE_SKYBEAM, me);
            me->SetDisplayId(me->GetCreatureTemplate()->Modelid2);
            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
        }

        void Reset() override
        {
            _targetGUID.Clear();
            _action = 3;
            _timer = 3000;
        }

        void UpdateAI(uint32 diff) override
        {
            if (_timer <= diff)
            {
                switch (_action)
                {
                    case 1:
                    {
                        _timer = 1000;

                        Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID);
                        if (target && me->IsInRange(target, 0.0f, 5.0f, false))
                        {
                            me->GetMotionMaster()->Clear();
                            me->GetMotionMaster()->MoveIdle();
                            _timer = 3000;
                            _targetGUID.Clear();
                            ++_action;
                        }
                        else if (!target)
                            _action = 3;

                        break;
                    }
                    case 2:
                        if (Creature* trigger = DoSummonFlyer(NPC_HODIR_BEACON, me, 50.0f, 0, 10000, TEMPSUMMON_TIMED_DESPAWN))
                        {
                            DoCast(trigger, SPELL_HODIR_S_FURY, true);
                            trigger->SetDisplayId(trigger->GetCreatureTemplate()->Modelid2);
                            ++_action;
                        }
                        _timer = 7000;
                        break;
                    case 3:
                        DoZoneInCombat(me, 200.0f);
                        if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                        {
                            _targetGUID = target->GetGUID();
                            me->GetMotionMaster()->MoveFollow(target, 0.0f, 0.0f);
                            _action = 1;
                        }
                        _timer = 5000;
                }
            }
            else
                _timer -= diff;
        }

        private:
            ObjectGuid _targetGUID;
            uint32 _timer;
            uint8 _action;
    };

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_hodirs_furyAI(creature);
    }
};

**Comment by M0ra** [comment]
Tested. hard for me, I'm from a mobile device

class npc_hodirs_fury : public CreatureScript
{
public:
    npc_hodirs_fury() : CreatureScript("npc_hodirs_fury") { }

```
struct npc_hodirs_furyAI : public ScriptedAI
{
    npc_hodirs_furyAI(Creature* creature) : ScriptedAI(creature)
    { 
        Initialize();
        me->setActive(true);
        me->SetReactState(REACT_PASSIVE);
        me->AddAura(SPELL_BLUE_SKYBEAM, me);
        me->SetDisplayId(me->GetCreatureTemplate()->Modelid2);
        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
    }

    void Initialize()
    {
        _targetGUID.Clear();
        _action = 3;
        _timer = 3000;
    }

    void Reset() override
    {
        Initialize();
    }

    void UpdateAI(uint32 diff) override
    {
        if (_timer <= diff)
        {
            switch (_action)
            {
                case 1:
                {
                    _timer = 1000;

                    Unit* target = ObjectAccessor::GetUnit(*me, _targetGUID);
                    if (target && me->IsInRange(target, 0.0f, 5.0f, false))
                    {
                        me->GetMotionMaster()->Clear();
                        me->GetMotionMaster()->MoveIdle();
                        _timer = 3000;
                        _targetGUID.Clear();
                        ++_action;
                    }
                    else if (!target)
                        _action = 3;

                    break;
                }
                case 2:
                    if (Creature* trigger = DoSummonFlyer(NPC_HODIR_BEACON, me, 50.0f, 0, 10000, TEMPSUMMON_TIMED_DESPAWN))
                    {
                        DoCast(trigger, SPELL_HODIR_S_FURY, true);
                        trigger->SetDisplayId(trigger->GetCreatureTemplate()->Modelid2);
                        ++_action;
                    }
                    _timer = 7000;
                    break;
                case 3:
                    DoZoneInCombat(me, 200.0f);
                    if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                    {
                        _targetGUID = target->GetGUID();
                        me->GetMotionMaster()->MoveFollow(target, 0.0f, 0.0f);
                        _action = 1;
                    }
                    _timer = 5000;
            }
        }
        else
            _timer -= diff;
    }

    private:
        ObjectGuid _targetGUID;
        uint32 _timer;
        uint8 _action;
};

CreatureAI* GetAI(Creature* creature) const override
{
    return new npc_hodirs_furyAI(creature);
}
```

};

**Comment by w5860363** [comment]
@M0ra Yes so I tested successfully before submitting the codes

**Comment by M0ra** [comment]
@w5860363  test script. I have no way.

**Comment by w5860363** [comment]
@M0ra I know I will test

**Comment by M0ra** [comment]
my English is bad. I Belarus

**Comment by w5860363** [comment]
I am Asian, please excuse my English.
