### ISSUE TITLE
0.0 can you push your database?good core,i want a try

### ISSUE THREAD

**Issue by planee** [M0ra/Core#2]
As title,if it's personal core,ignore me pls.

**Comment by M0ra** [comment]
My personal core, sorry

**Comment by iraj0711** [comment]
closed? but core can not bulding ? very very crezy

**Comment by M0ra** [comment]
@iraj0711 I'm not interested in your problems.

**Comment by iraj0711** [comment]
So do not solve the problem compile?

**Comment by iraj0711** [comment]
So do not solve the problem compile? 

```
 On Saturday, May 2, 2015 12:47 PM, Alex <notifications@github.com> wrote:
```

 @iraj0711 I'm not interested in your problems.—
