### ISSUE TITLE
Fix :)

### ISSUE THREAD

**Issue by shorden** [M0ra/Core#3]

**Comment by shorden** [comment]
diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
index 59971c1..ffb9c9f 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
@@ -230,7 +230,7 @@ class boss_kologarn : public CreatureScript
                 }
             }

--           uint32 GetData(uint32 type)
++       uint32 GetData(uint32 type)const override
             {
                 switch (type)
                 {

**Comment by M0ra** [comment]
@shorden Thank you, I know, then Ulduar)
