### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by AniRB** [M0ra/Core#4]
Добрый день!

Подскажите пожалуйста что за разботка ядра у вас видеться?

**Comment by M0ra** [comment]
@AniRB Добрый вечер.
Обычное ядро. К чему такие вопросы?

**Comment by AniRB** [comment]
Жаль что тут нет личных сообщений, как можно с вами связаться?

**Comment by M0ra** [comment]
@AniRB Skype: susl1k9
