### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Kenny-w** [M0ra/Core#6]
I come from Chinese, your project is very good, my English is very poor, do not know if you can understand what I mean?
I use the following error when the VS2013 compiler, please help me, thank you:

> game.lib(WorldSocketMgr.obj) : error LNK2005: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) 已经在 RASession.obj 中定义
> 3>game.lib(ObjectMgr.obj) : error LNK2005: "public: static int const ReputationMgr::Reputation_Cap" (?Reputation_Cap@ReputationMgr@@2HB) 已经在 game.lib(ConditionMgr.obj) 中定义
> 3>F:\ElunaTrinityWotlk\trunk\win\bin\Release\worldserver.exe : fatal error LNK1169: 找到一个或多个多重定义的符号

**Comment by M0ra** [comment]
Pls pastebin
